application: iq
version: 2
runtime: python
api_version: 1

handlers:
- url: /legacy/.*
  script: legacy.py
- url: /(.*\.(css|js))
  static_files: \2/\1
  upload: (css|js)/(.*)
  expiration: 1d
- url: /.*
  script: web.py
