application: iq
version: 1
runtime: python
api_version: 1

handlers:
- url: /legacy/.*
  script: legacy.py
- url: /(.*\.(css|js))
  static_files: \2/\1
  upload: (.*)/(.*)
  expiration: 1d
- url: /.*
  script: web.py
